language: cpp
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python-serial srecord
install:
- wget https://github.com/GeorgeHahn/nodemcu-firmware/raw/travis/tools/esp-open-sdk.tar.gz -O tools/esp-open-sdk.tar.gz
- tar -zxvf tools/esp-open-sdk.tar.gz
- export PATH=$PATH:$PWD/esp-open-sdk/sdk:$PWD/esp-open-sdk/xtensa-lx106-elf/bin
- wget http://bbs.espressif.com/download/file.php?id=1046 -O tools/esp_iot_sdk_v1.5.1.zip
- unzip tools/esp_iot_sdk_v1.5.1.zip
script:
- make all SDK_BASE="$PWD/esp_iot_sdk_v1.5.1"
- cd firmware/
- file_name="esp_mqtt_v${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}.bin"
- srec_cat -output ${file_name} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x40000 0x40000.bin -binary -offset 0x40000
deploy:
provider: releases
api_key:
file: "$TRAVIS_BUILD_DIR/firmware/${file_name}"
skip_cleanup: true
on:
tags: true
repo: tuanpmt/esp_mqtt
